name: notes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.1 <4.0.0"

dependencies:
    adwaita: ^1.1.0
    flutter:
        sdk: flutter
    flutter_quill: ^9.5.3
    handy_window: ^0.4.0
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    path_provider: ^2.1.3
    provider: ^6.1.2
    reorderable_grid_view: ^2.2.6
    shared_preferences: ^2.2.3
    yaru: ^4.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    build_runner: ^2.4.11
    isar_generator: ^3.1.0+1

flutter:
    uses-material-design: true

    fonts:
        - family: RobotoMono
          fonts:
              - asset: fonts/RobotoMono-Bold.ttf
                weight: 700
              - asset: fonts/RobotoMono-Light.ttf
                weight: 300
        - family: Roboto
          fonts:
              - asset: fonts/Roboto-Bold.ttf
                weight: 700
              - asset: fonts/Roboto-Light.ttf
                weight: 300
        - family: NotoSans
          fonts:
              - asset: fonts/NotoSans-Bold.ttf
                weight: 700
              - asset: fonts/NotoSans-Light.ttf
                weight: 300
